import type { Metadata } from "next"
import { AIChatProvider } from "@/components/ai-chat/ai-chat-provider"
import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <AIChatProvider>
        <body className="antialiased">{children}</body>
      </AIChatProvider>
    </html>
  )
}
